name: "buildx"

on:
  push:
    paths:
      - 'src/**'

jobs:
  build-vue:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'src/vue/') }}
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      # build
      - name: build 1
        shell: pwsh
        working-directory: ./build
        run: |
          Write-Host "Build vue!!!!"

  build-dotnet:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.modified, 'src/dotnet/') }}
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      # build
      - name: build 1
        shell: pwsh
        working-directory: ./build
        run: |
          Write-Host "Build dotnet!!!!"

  deploy:
    runs-on: ubuntu-22.04
    needs: [ build-dotnet, build-vue ]
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      # build
      - name: build 1
        shell: pwsh
        working-directory: ./build
        run: |
          Write-Host "Deploy!!!!"