name: "buildx"

on:
  push:
    paths:
      - 'src/**'

jobs:
  build-vue:
    runs-on: ubuntu-22.04
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      # path filter
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'src/vue/**'
      # build
      - name: build 1
        if: steps.changes.outputs.src == 'true'
        shell: pwsh
        working-directory: ./build
        run: |
          Write-Host "Build vue!!!!"

  build-dotnet:
    runs-on: ubuntu-22.04
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      # path filter
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'src/dotnet/**'
      # build
      - name: build 1
        if: steps.changes.outputs.src == 'true'
        shell: pwsh
        working-directory: ./build
        run: |
          Write-Host "Build dotnet!!!!"

  deploy:
    runs-on: ubuntu-22.04
    needs: [ build-dotnet, build-vue ]
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      # build
      - name: build 1
        shell: pwsh
        working-directory: ./build
        run: |
          Write-Host "Deploy!!!!"
