name: "buildx"

on:
  push:
    paths:
      - 'src/vue/**'


jobs:
  build-vue:
    runs-on: ubuntu-22.04
    name: Build vue
    steps:
      # checkout source code
      - uses: actions/checkout@v2
      # build
      - name: build 1
        shell: pwsh
        working-directory: ./build
        run: |
          Write-Host "Build Vue!!!!"
